### ISSUE TITLE
HLCA Full Seurat?

### ISSUE THREAD

**Issue by Dzhan4** [LungCellAtlas/HLCA#11]
From the CZI website it states that the limitations of R dgCMatrix prevent a seurat object download for the full dataset. 

Since there are newer methods to convert large h5ad dataset to seurat objects, is it worth attempting this conversion? Or is there some fixed reason why a seurat object cannot be used to include the full dataset?

Thank you!

**Comment by LisaSikkema** [comment]
Hi @Dzhan4 , I am not very knowledgeable on the subject as I haven't used the HLCA in R myself yet, but my understanding is that the R object is simply too large to work with in R. Would the new conversion method create a smaller R object? In that case it might be worth trying. People from cellxgene would probably have better advice here..
I know that you can also use census from cellxgene (https://chanzuckerberg.github.io/cellxgene-census/) to subset the object before downloading, which should enable you to download and work with a subset of the data in Seurat, if you don't need all data.

**Comment by HendricksJudy** [comment]
Analyzing such a vast dataset (About 22Gb) in R language is possible. However, due to the memory management feature of R language, it may need 64G RAM or even more (My environment has 128GB RAM)  to ensure an acceptable experience. And it is so slow that one command operating in R may waste minutes. It is better to try the cellxgene or python 😃
