### ISSUE TITLE
Squamous cells

### ISSUE THREAD

**Issue by jackwgoodall** [LungCellAtlas/HLCA#14]
Hi HLCA team,
Thank you for an amazing resource! 
We were a little surprised not to see squamous cells in the final annotation.  Is there a reason they aren't there? 
Many thanks
Jack

**Comment by LisaSikkema** [comment]
Hi Jack, apologies for the late reply! Currently on parental leave so not the best at checking GitHub issues atm. I discussed with the people who helped us annotate, and they said we left those annotations out because there wasn't a clear consensus yet on their definition. They were annotated in a couple of datasets originally though, you can find those under original_ann_level_3 (you might have noticed those already). Hope that helps!

**Comment by jackwgoodall** [comment]
This is really helpful - thank you!
