### ISSUE TITLE
Cell type labels differ between Celltypist and Azimuth

### ISSUE THREAD

**Issue by SirKuikka** [LungCellAtlas/HLCA#17]
Hi,

Celltypist can predict Hillock-like cells, but Azimuth doesn't have that option. https://azimuth.hubmapconsortium.org/references/#Human%20-%20Lung%20v2%20%28HLCA%29

I wonder what is the reason for the difference? 

Are the scArches labels listed somewhere?

**Comment by LisaSikkema** [comment]
Hello! Oh that's unexpected, what does Azimuth give you then?

**Comment by SirKuikka** [comment]
It's the cell types listed on that web page I shared. There's no "hillock-like". But Celltypist predicted Hillock-like cells.

Please click below "Annotation Details"

**Comment by LisaSikkema** [comment]
Oh I see it now, it's not in the list of annotations that Azimuth somehow puts below the dataset. It's weird because when I look at the actual annotations in the dataset there (when you click on Reference) I see the Hillock-like cells in the annotation (in ann_finest_level for example).
I don't know how Azimuth comes up with the list of cell types you mentioned, it is something you would have to contact them about. It seems like some weird glitch in their set-up...

**Comment by SirKuikka** [comment]
Hi, ok. I can also test scArches. But good to know that the Hillock-like cells should be there.

**Comment by SirKuikka** [comment]
But actually,  how come Celltypist has only one annotation level whereas scArches and Azimuth have 5 or 6?

**Comment by LisaSikkema** [comment]
That I also don't know, they set up the model. Apparently they decided to only include the finest level. We could ask them to include all levels, it would be nice. 
Either way you can of course get the coarser levels of annotations from the finer ones (see [this table](https://github.com/LungCellAtlas/HLCA_reproducibility/blob/main/supporting_files/celltype_structure_and_colors/manual_anns_and_leveled_anns_ordered.csv)) but that doesn't give you the uncertainties for the lower levels, which is useful to have.

**Comment by SirKuikka** [comment]
Thank you!
